### ISSUE TITLE
Remove Gradle files

### ISSUE THREAD

**Issue by Goldorion** [NerdyPuzzle/Fabric-Essentials#1]
I included what you needed in the build.gradle and gradle.properties files in the last update of the Fabric Generator, so you don't need to override them anymore.

**Comment by NerdyPuzzle** [comment]
Removed them + merged files froms PRs

**Comment by Goldorion** [comment]
You can use words such as Close, Closes, Fix and Fixes #theissuenumber to automatically close and link the PR and an issue.
