### ISSUE TITLE
[Feature Request] Variables Update

### ISSUE THREAD

**Issue by sakusakus** [NerdyPuzzle/Fabric-Essentials#14]
Hi! I saw on mcreator forums back in Dec that you were planning to add the player_persistant variable in the next update- wondering if that made it in to the most recent one? If not, no worries! I can wait. Thanks for all your hard work!

**Comment by NerdyPuzzle** [comment]
They are implemented already in the form of procedure blocks. Check the Fabric Variables category in procedures.

**Comment by sakusakus** [comment]
thats awesome thank you!
