### ISSUE TITLE
The 'RepairItemRecipeMixin' is not present in the mod

### ISSUE THREAD

**Issue by PSGitHubUser1** [NerdyPuzzle/Fabric-Essentials#3]
![image](https://user-images.githubusercontent.com/90406016/207848694-e5269d2f-406c-45fe-a550-11dd5a31350a.png)

When loading game, it's showing this.. When I extracted the mod and open the "net.mojang.portdiscs" then there is no 'mixin' folder.
That's why game is not loading.. fix this please @NerdyPuzzle.

**Mod name >> PortDiscs**

**I am using the latest version of "MCreator 2022.3" and latest version of this plugin (v1.6)**

**Comment by NerdyPuzzle** [comment]
Have you updated to fabric generator 1.8? The mixin that's missing here was added in that version.

**Comment by PSGitHubUser1** [comment]
> Have you updated to fabric generator 1.8? The mixin that's missing here was added in that version.

yes. I have updated...
  I know it was the bug no. #309 in Fabric Generator.

But if you're are saying then I am reinstalling the fabric now.

**Comment by NerdyPuzzle** [comment]
can you test that this also happens in a new workspace?

**Comment by PSGitHubUser1** [comment]
Ok. But I am thinking that its a bug..

**Comment by NerdyPuzzle** [comment]
I need to know when it happens if it is a bug. Tell me what happens if you use a new workspace.

**Comment by PSGitHubUser1** [comment]
> I need to know when it happens if it is a bug. Tell me what happens if you use a new workspace.

No, the mixin is still not present in a new workspace. Even after enabling the Porting-Lib/Fabric Essentials
![image](https://user-images.githubusercontent.com/90406016/207889052-48d006af-d6b8-40d3-8c15-307c510212f3.png)

And also it crashed again. Now I it is proved that it's a bug. (I guess? yes or no?)

**Mod name >> TestMod**


_Hey, I just saw this, the new version of Porting-Lib is posted on curseforge, import that mod in this plugin may fix this problem?_

![image](https://user-images.githubusercontent.com/90406016/207890371-b79c780d-2106-4f5b-9158-eb25a25fc1c0.jpg)
![image](https://user-images.githubusercontent.com/90406016/207890528-7b2a2d3c-eb42-4d6a-beb3-7453f6fb3cb9.png)

**Comment by PSGitHubUser1** [comment]
> I need to know when it happens if it is a bug. Tell me what happens if you use a new workspace.

Reply me. Is it a bug or not?

**Comment by NerdyPuzzle** [comment]
![Screenshot_951](https://user-images.githubusercontent.com/112079900/207897662-066e5039-733a-404b-a7b2-d503a115c7e9.png)
Testing fabric generator 1.8 and fabric essentials 1.6, I do not get the same result. The mixin generates, and the game launches.

**Comment by NerdyPuzzle** [comment]
This could be due to you having 2 versions of the plugin loaded at the same time. Check that it is not the case.

**Comment by PSGitHubUser1** [comment]
![image](https://user-images.githubusercontent.com/90406016/207901358-1580751a-5822-48b5-b736-f94fe0c2676d.png)
But...?

**Comment by PSGitHubUser1** [comment]
> This could be due to you having 2 versions of the plugin loaded at the same time. Check that it is not the case.

That's not the case..

UPDATE: I remembered something, when I download the updates then my gradle project always (almost) rebuild but this time it doesn't.. Even after adding the Porting-Lib/Fabric Essentials. Maybe that can be the problem can you explain me?

**Comment by NerdyPuzzle** [comment]
I found the bug. The mixins for items would generate in the mixins.json even if items were not present in the workspace anymore. Will fix it in a patch release.

**Comment by PSGitHubUser1** [comment]
> I found the bug. The mixins for items would generate in the mixins.json even if items were not present in the workspace anymore. Will fix it in a patch release.

Wait, I didn't understand what you want to say, in my workspace there are more then 3 blocks, 25+ items..?
If you have to verify/check then go to this website (my mod): https://www.curseforge.com/minecraft/mc-mods/portdiscs-fabric-port 
Can't you post a subversion? like FE 1.6.1 or FE 1.6.01 something like that?

**Comment by NerdyPuzzle** [comment]
yes. that is what I will do.

**Comment by PSGitHubUser1** [comment]
Updated the last comment (Edited)

**Comment by PSGitHubUser1** [comment]
> yes. that is what I will do.

Oo. Ok

**Comment by NerdyPuzzle** [comment]
It seems music discs generate the mixins.json but don't generate the mixin. I'll look into that.

**Comment by NerdyPuzzle** [comment]
(a temporary solution for you is adding an item)

**Comment by PSGitHubUser1** [comment]
> (a temporary solution for you is adding an item)

what item? (actually it's a fabric ported mod of a orginal mod whichi is in forge), so I can't add anything myself until the author permit me. I will wait for the patch release. 2-3 days or 4? 

Already there are 25+ item/music disc and some ranged item (2)

**Comment by NerdyPuzzle** [comment]
it is only a matter of updating 3 lines of code, so the release will be today. The issue is that the mixin doesn't generate for music discs, but the game tries to load it anyway. To generate the mixin, an item needs to be part of a workspace at the moment.

**Comment by PSGitHubUser1** [comment]
> it is only a matter of updating 3 lines of code, so the release will be today. The issue is that the mixin doesn't generate for music discs, but the game tries to load it anyway. To generate the mixin, an item needs to be part of a workspace at the moment.

wait, not only music discs, because my mod also contains ranged item (2 items) maybe ranged items can cause this problem??
(even the mod contains blocks so please confirm which one of them is causing problem, in my opinion, its ranged item)

**Comment by NerdyPuzzle** [comment]
ranged items dont use the mixin. Only tools and normal items do.

**Comment by PSGitHubUser1** [comment]
> ranged items dont use the mixin. Only tools and normal items do.

Thanks for this. I thought that the Generator has a problem. Yesterday, I updated my workspace to 1.8.. cause 1.7 caused the export mod error (#313 in Fabric Generator Issue tab)

**Comment by NerdyPuzzle** [comment]
it is an error in the generator, one which I will fix through the plugin.

**Comment by PSGitHubUser1** [comment]
> it is an error in the generator, one which I will fix through the plugin.

OOOO. Means I thought right (by chance) !! 
I am not disturbing you now, just update that 3 lines. But report to Goldorion

**Comment by NerdyPuzzle** [comment]
Latest commit fixes this, will release soon.

**Comment by PSGitHubUser1** [comment]
![image](https://user-images.githubusercontent.com/90406016/207917860-24cd568b-293d-496e-93cb-874199115ea0.png)
It didn't worked!?

**Comment by PSGitHubUser1** [comment]
> Latest commit fixes this, will release soon.

Yes, It didn't worked again.. (v1.6.1)
