### ISSUE TITLE
[BugFix Request] The structure do not spawn where they should spawn #321 and #348

### ISSUE THREAD

**Issue by PSGitHubUser1** [NerdyPuzzle/Fabric-Essentials#5]
### Issue description

#321 [Fabric Generator github page] - Reported by me

Structures are still not spawning where they are supposed to.. (even after setting 'First Block')
![2022-12-16_09 58 09](https://user-images.githubusercontent.com/90406016/208024645-5929c960-13d5-41c9-8b98-9b3c9c36f771.png)
![2022-12-04_13 48 07](https://user-images.githubusercontent.com/90406016/208024667-efc7f377-00f5-4eea-b178-abaceb1f4295.png)
![2022-12-28_12 37 13](https://user-images.githubusercontent.com/90406016/209777188-0f1b3e1d-8965-4255-ac82-cfcd2ec09a93.png)
![2022-12-28_12 37 20](https://user-images.githubusercontent.com/90406016/209777198-86eee8fc-00f5-4f95-a3dc-0c54413eba91.png)
![2022-12-28_12 42 52](https://user-images.githubusercontent.com/90406016/209777212-4b03752c-292a-49a9-a474-0e21828b76a2.png)
![2022-12-28_12 43 03](https://user-images.githubusercontent.com/90406016/209777219-336f6e33-fed1-4918-877e-f7ae107f780a.png)

### How to reproduce this issue?

1. Make a fabric workspace
2. Create a structure
3. Set it as 'First Block' 
4. Set to spawn in desert or plains
5. Export mod and run in game
6. You will see that the structure is spawning in 'warm_ocean' or other ocean (mostly in 'warm_ocean')
7. Structure is not spawning in water or underwater ( #321 ) but spawning on the water (Surface level of water)

### Operating system

Windows

### Details

MCreator version: 2022.3
Fabric Generator version: v1.8 (latest)
Fabric Essentials plugin/Porting-Lib version: v1.6.2 (latest)

### Example workspace

My workspace is example

**Comment by PSGitHubUser1** [comment]
@NerdyPuzzle or @kleiders3010 or @Goldorion  Please provide your Discord. I can't just create new bugs to issue you.

It is better to just talk with you on discord. 
 If you ask in terms of privacy, then send me your discord id in personal here (I will be waiting): https://www.curseforge.com/members/infoytechtv/projects 
 
 So that nobody except me can take your id and just send you friend request
 
 Thanks.

**Comment by kleiders3010** [comment]
Workspace example is for you to upload your workspace's zip, please upload it with only the element of the bugged structure @PSGitHubUser1

**Comment by PSGitHubUser1** [comment]
> Workspace example is for you to upload your workspace's zip, please upload it with only the element of the bugged structure @PSGitHubUser1

Can you send your Discord ID or say @NerdyPuzzle to send his Discord ID??

I cannot send the workspace as it is larger than 25 MB (GitHub Upload Limit), its 40 MB large.
_And All structures are bugged (Not sure for Nether and End structures, but sure for Overworld structure.)_ 

Requirements:   
---
1. TerraBlender (Fabric) 
2. Fabric Generator
3. Fabric Essentials or Porting-Lib
--------------------------------------------------------
But I am sending you in MediaFire: https://www.mediafire.com/file/17bpyp85liixjah/portdiscs_workspace_v0.8-1.19.2.zip/file

**Comment by PSGitHubUser1** [comment]
it is fixed?

**Comment by kleiders3010** [comment]
2 things:
1. Example workspace should include only 1 or 2 examples of the issue and ONLY the issue
2. We do not support privately through discord.

**Comment by PSGitHubUser1** [comment]
> 2 things:
> 
> 1. Example workspace should include only 1 or 2 examples of the issue and ONLY the issue
> 2. We do not support privately through discord.

Ok. But now what I do? I made 3 mods and the structures are spawning as "First block" on water in lakes, ocean etc. I made a christmas tree and want to spawn around Spruce trees. But its spawning on water and in oaks, birchs. So help me, how do I fix my code? 😞 😭

**Comment by NerdyPuzzle** [comment]
Use an additional generation condition or restrict the biomes.

**Comment by PSGitHubUser1** [comment]
Its not working on restrict the biomes. See 😭 
![image](https://user-images.githubusercontent.com/90406016/209835697-803ac864-070a-4be7-94c6-adf34b05f56c.png)

And how to use additional generation condition, I made procedure, but I can't set it as like 'This is the procedure, use this to generate structures.'

**Comment by kleiders3010** [comment]
Which biomes do you have selected? I see that you marked it to spawn only on water, it seems to be working as intended

**Comment by PSGitHubUser1** [comment]
no no. its restricted block types.

**Comment by PSGitHubUser1** [comment]
where the structure should 'not' (according to written there) spawn so I added water.

**Comment by PSGitHubUser1** [comment]
Also using this block is causing compile error: 

![image](https://user-images.githubusercontent.com/90406016/209836445-e10c3ad9-c38c-4061-a450-e0ed4b7e25d8.png)
![image](https://user-images.githubusercontent.com/90406016/209836488-7bc0c5c7-af92-4d0b-a846-a1b93cb80591.png)
![image](https://user-images.githubusercontent.com/90406016/209836558-fe1194db-8493-4b27-bcb1-02f0dfe52fcc.png)
The error is caused by the highlighted text. (According to MCreator)

**Comment by NerdyPuzzle** [comment]
You restricted it to only spawn in water... restrict block types are the blocks in spawns on...

**Comment by PSGitHubUser1** [comment]
OOOOO...

**Comment by PSGitHubUser1** [comment]
Mean I have to set desert biome only to spawn in it?!!

**Comment by PSGitHubUser1** [comment]
Thanks for help. I closing this 'misunderstand' issue.
