### ISSUE TITLE
[Feature Request] Add support for Villager trades

### ISSUE THREAD

**Issue by PSGitHubUser1** [NerdyPuzzle/Fabric-Essentials#6]
Check out - #348 [Fabric Generator github page]
-----------------------
I want this feature my mod and its required for my fabric ported mod. Please add Villager trades.

 I opened the MC 1.19.2 game files and checked out 'Villager Trades' and they are simple.
 
 -------------------------------------------------------------
 

_For Fabric Essentials (@NerdyPuzzle)_

You can add Architectury API for Villager Trade support or add this mod in your plugin https://www.curseforge.com/minecraft/mc-mods/custom-villager-trades-fabric/files/4175948

**Comment by PSGitHubUser1** [comment]
@NerdyPuzzle or @kleiders3010 or @Goldorion  Please provide your Discord. I can't just create new bugs to issue you.

It is better to just talk with you on discord. 
 If you ask in terms of privacy, then send me your discord id in personal here (I will be waiting): https://www.curseforge.com/members/infoytechtv/projects 
 
 So that nobody except me can take your id and just send you friend request
 
 Thanks.

**Comment by PSGitHubUser1** [comment]
@kleiders3010 @NerdyPuzzle Can you add this #feature please? 
If I knew Java then I would help you.

**Comment by kleiders3010** [comment]
Do not ping on requests that are already open

**Comment by PSGitHubUser1** [comment]
:|

**Comment by PSGitHubUser1** [comment]
Done, I guess this is hard #feature.. It requires heavy coding. That's why its taking long. [Sorry for the disturbance]

**Comment by PSGitHubUser1** [comment]
Is it done... I should not ask but I don't know why I'm losing my patience.

**Comment by PSGitHubUser1** [comment]
.... uhh. ok

**Comment by PSGitHubUser1** [comment]
The new snapshot is here (2023.1 - b08712).

but the thing is, I am just waiting for Villager trade feature in Fabric. `=]`

Well, once somebody said,
`"Patience is the key of door for a new update.`
