### ISSUE TITLE
[BugFix Request] Gradle Dependencies are not loading on creating a new workspace

### ISSUE THREAD

**Issue by PSGitHubUser1** [NerdyPuzzle/Fabric-Essentials#7]
### Issue description

 I made a new workspace and its not loading even after clicking on "Yes, refactor workspace" on enabling Fabric Essentials and TerraBlender.

-------------------------------

### Update
I removed the Fabric Essentials and the workspace is working fine.. means Porting-Lib/Fabric Essentials is causing problem, not the generator so I closed the issue from https://github.com/Goldorion/Fabric-Generator-MCreator/issues and made this issue here. 

![image](https://user-images.githubusercontent.com/90406016/209502705-89f1bc28-3845-4025-8639-a3f3854d3e50.png)
This is picture after removing Fabric Essentials and making an new workspace... 

-------------------------------

### Info
Actually, when loading this plugin and then making a new workspace is causing the External Libraries to not generate. But maybe after generating libraries and loading this plugin may not cause this error.

UPDATE: Its still causing error even after making a workspace without FE (Fabric Essentials) and then loading the plugin.. and clicking on "Yes, refactor workspace" on click on green tick mark. Means something is there which is causing problem in plugin 
![image](https://user-images.githubusercontent.com/90406016/209503813-96a2404c-c596-4efe-baa2-46836a8ebd75.png)

Fabric Essentials version: 1.6.2 (latest)
@NerdyPuzzle @kleiders3010 Please fix this ASAP.
-------------------------------
 
 Video: https://drive.google.com/file/d/1vkB5taPXcAts7dqrlejQGjuq0M3qmKpa/view?usp=share_link

### How to reproduce this issue?

1. Make a new workspace
2. Wait for it to build
3. You can see the problem that Gradle Dependencies are not loading

### Operating system

Windows

### Details

MCreator version: 2022.3 (do not want to use 2022.4 snapshot)
Fabric Generator: 1.8.1 (because 1.8.2 only support to 2022.4 snapshot)
Fabric Essentials: 1.6.2

### Example workspace

Trying to send a video...
Workspace cannot be sent.
https://drive.google.com/file/d/1vkB5taPXcAts7dqrlejQGjuq0M3qmKpa/view?usp=share_link

### Logs

No logs available, its just says "BUILD FAILED" doesn't tell that which line caused error..

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by kleiders3010** [comment]
Fixed on 1.6.3
