### ISSUE TITLE
The loader reported an error while loading two mods built from this api simultaneously

### ISSUE THREAD

**Issue by RegulusSource** [NerdyPuzzle/Fabric-Essentials#8]
The loader reported an error while loading two mods built from this api simultaneously

**Comment by NerdyPuzzle** [comment]
Please provide the crashlog.

**Comment by RegulusSource** [comment]
[crash-2023-01-15_01.25.16.7440-quilt_loader.txt](https://github.com/NerdyPuzzle/Fabric-Essentials/files/10419436/crash-2023-01-15_01.25.16.7440-quilt_loader.txt)

**Comment by NerdyPuzzle** [comment]
Most Fabric mods may load on quilt, but this does not mean that they support it. Unless you get this crash while using the Fabric loader, this is invalid.

**Comment by NerdyPuzzle** [comment]
It was a bug, but not with this plugin but the generator itself.
